# deploy.yml
name: retrocode.io to cloud.tencent
on:
  push:
    branches:
      - main
jobs:
  build:
    # 运行环境:ubuntu
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@main
#       # 下载 git submodule
#       - uses: srt32/git-actions@v0.0.3
#         with:
#           args: git submodule update --init --recursive
      # 使用 node:10
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: ll
        run: |
          ls -l /home/runner/work/retrocode.io
#       # npm install
#       - name: npm install
#         run: |
#           npm install -g hexo-cli
#           npm install
#         env:
#           CI: true
#       # build
#       - name: hexo build
#         run: |
#           hexo clean
#           hexo generate
#         env:
#           CI: true

      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          # 直接部署整个项目
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
